
public enum GameEvent {
	None,
	GameState_GameStarted,
	GameState_GameOver,
	Organization_CommandPoolChanged,
	Organization_Initialized,
	Organization_HenchmenHired,
	GameState_TurnNumberChanged,
	Organization_HenchmenDismissed,
	Henchmen_MissionStarted,
	Henchmen_MissionCompleted,
	Henchmen_MissionContinued,
	Organization_HenchmenForHireArrived,
	Henchmen_ArriveInRegion,
	Organization_InfamyChanged,
	Organization_AssetGained,
	ActivityMenu_TurnResultsChanged,
	Mission_AssetLaunched,
	Mission_AssetUsed,
	Region_ControlTokenSeized,
	Region_TokenStatusChanged,
}
